[project]
name = "dbt-walmart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tan Nguyen", email = "nghoangtan96@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "airflow-operators>=0.11.0",
    "apache-airflow>=3.3.2",
    "databricks-sdk>=0.47.0",
    "dbt-core>=1.12.5",
    "dbt-databricks>=1.10.9",
]

[project.scripts]
dbt-walmart = "dbt_walmart:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
